// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsLwO-inGMw3dw-OsuNkpNNlFcpJW2b3A',
    appId: '1:5299793812:android:7bf2b0eb91a2479334a981',
    messagingSenderId: '5299793812',
    projectId: 'tracktor-firebase',
    storageBucket: 'tracktor-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsbHPhl9a3pTeeIUzUElrTUNTDdChnqQI',
    appId: '1:5299793812:ios:63dd7a5a23ae700e34a981',
    messagingSenderId: '5299793812',
    projectId: 'tracktor-firebase',
    storageBucket: 'tracktor-firebase.firebasestorage.app',
    androidClientId: '5299793812-m5ur7q2t6rolo2b3v7erdb9vpdgeq0jc.apps.googleusercontent.com',
    iosClientId: '5299793812-2ejv76ebjapqveo4qcabldggbtlsb4ah.apps.googleusercontent.com',
    iosBundleId: 'com.baazinfotech.tracktor',
  );
}
